[tool.poetry]
name = "playbook-test"
version = "0.1.0"
description = ""
authors = ["Damien RIDEREAU <damien.ridereau@systeme-u.fr>"]

[tool.poetry.dev-dependencies]
robusta-cli = "^0.10.9"
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
